name: Update WeChat News

on:
  schedule:
    - cron: "0 1,4,7,10,13,16,19,22 * * *"  # giờ VN tương đương mỗi 3h
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run update script
        run: python update_news.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add news.json news_full.html
          git commit -m "Update news.json and news_full.html" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
