name: Update WeChat News

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write   # 🚨 Thêm đoạn này ngay đây, cùng cấp với 'on'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python update_news.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add news.json
          git commit -m "Update news.json" || echo "No changes"
          git push
